version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  api:
    build: .
    image: rockz5555/api
    env_file:
      - ./.env
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=nijoo
      - MONGO_INITDB_ROOT_PASSWORD=12345
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis:alpine

volumes:
  mongo-db:
