apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-api
spec:
  replicas: 5
  selector:
    matchLabels:
      app: express-api
  template:
    metadata:
      labels:
        app: express-api
    spec:
      containers:
      - name: express-api
        image: rockz5555/express-api
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: express-api
spec:
  type: LoadBalancer
  selector:
    app: express-api
  ports:
  - port: 3030
    targetPort: 3000
